name: polyline_tools
description: "A Dart package for encoding and decoding Google Maps polylines."
version: 0.0.1
author: Natnael Alemseged <natiaabaydam@gmail.com>
repository: https://github.com/Natnael-Alemseged/polyline_tools.git
homepage: https://pub.dev/packages/polyline_tools

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages

# Fonts can be added here, if needed.
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
